version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - yarn install --pure-lockfile

  build:
    commands:
      - npx nx build not-your-chat

  post_build:
    commands:
      - mv dist/apps/not-your-chat build_output/not-your-chat-app

artifacts:
  files:
    - build_output/not-your-chat-app/**/*
  name: not-your-chat-app
