version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - yarn install --pure-lockfile

  build:
    commands:
      - npx nx build not-your-chat

artifacts:
  files:
    - dist/apps/not-your-chat/**/*
