version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - yarn install --pure-lockfile

  build:
    commands:
      - npx nx build not-your-chat

  post_build:
    commands:
      - zip -r not-your-chat.zip ./dist/apps/not-your-chat

artifacts:
  files:
    - not-your-chat.zip
  name: not-your-chat
