version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - ls -lf

  build:
    commands:
      - aws s3 cp ./not-your-chat-app s3://not-your-chat-app --acl public-read

  post_build:
    commands:
      - ls -lf
