version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: latest

  pre_build:
    commands:
      - ls -lf
      - npm i
  build:
    commands:
      - npx nx run not-your-chat:lint --outputFile=not-your-chat-lint-report.trx
  post_build:
    commands:
      - ls -lf
reports:
  lint-report:
    files:
      - not-your-chat-lint-report.trx
    file-format: visualstudio
