version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - yarn install --pure-lockfile

  build:
    commands:
      - npx nx run not-your-chat:lint --outputFile=not-your-chat-lint-report.trx

reports:
  lint-report:
    files:
      - not-your-chat-lint-report.trx
    file-format: visualstudio
