version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: latest

  pre_build:
    commands:
      - ls -lf
      - npm i
  build:
    commands:
      - npx nx run not-your-chat:test --ci --coverage
  post_build:
    commands:
      - ls -lf
reports:
  not-your-chat-test-report:
    files:
      - coverage/apps/not-your-chat
