version: 0.2

env:
  variables:
    NODE_ENV: test
    BABEL_ENV: test

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - yarn install --pure-lockfile

  build:
    commands:
      - ls -lf
      - echo END OF ROOT LS LF
      - echo BLANK LINE
      - echo BLANK LINE
      - echo BLANK LINE
      - cd apps/not-your-chat && ls -lf
      - cd ../..
      - npx nx test not-your-chat --ci --coverage --skip-nx-cache #--showConfig

reports:
  not-your-chat:
    files:
      - 'coverage/apps/not-your-chat/**/*'
