version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: latest

  pre_build:
    commands:
      - ls -lf
      - npm i
  build:
    commands:
      - npx nx test not-your-chat
  post_build:
    commands:
      - ls -lf
artifacts:
  files:
    - dist/apps/not-your-chat
