version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: latest

  pre_build:
    commands:
      - yarn install

  build:
    commands:
      - npx nx test not-your-chat --ci --coverage --skip-nx-cache

reports:
  not-your-chat:
    files:
      - coverage/apps/not-your-chat
